# Site settings
title: Evelien Baur
email: EvelienBaur@hotmail.com
url: https://example.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Zelfontwikkeling - Zingeving - Zelfbewustzijn - Zelfkennis - Autonomie"
meta_author: Baur Evelien

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: C2185B #80B3FF #18bc9c
  primary-rgb: "240,98,146" #"24,288,156" #"128,179,255"
  secondary: E91E63 #FD6E8A #2c3e50 #
  secondary-dark: F06292 #233140 #A2122F

# Footer settings
footer:
  copyright: JB productions
  location: Locatie
  social: Bereikbaar op het web
  credits: Zin in thee?

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: instagram
    url: 
  - title: pinterest
    url: 
  - title: linkedin
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: Valder 42
  - line: 6373 TB Landgraaf

# Credits content
credits: 'Bedankt voor het bezoeken van mijn website. Ben je geïnteresseerd en wil je meer weten? De thee staat klaar!'

# Build settings
markdown: kramdown
permalink: pretty
